# https://github.com/ligurio/trinity/blob/travis-ci/.travis.yml
# https://github.com/protobuf-c/protobuf-c/blob/master/.travis.yml

language:
    - c
    - cpp

compiler:
    - gcc
    - clang

before_install:
    - sudo apt-get update -qq

install:
  - sudo apt-get install bash make

before_script: "bash ./configure.sh"

script:
    - ( cd Sources && ./Gen.py && make -j2 )

install:
    - ( cd Sources && ./Gen.py && make -j2 )

notifications:
  email:
    recipients:
      - estetus@gmail.com
    on_success: change
    on_failure: always
