language: cpp

compiler: gcc

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install make g++ qt4-qmake libqt4-dev lib32z1-dev

script:
    - ( cd Sources && ./Gen.py; cd - )
    - ( cd Sources/XmlModel/Utils/xsd2src/ && qmake-qt4 && make -j2 && cd - )
    - ( cd Sources && ./Gen.py && cd SDK && qmake && make -j2 && sudo make install )

notifications:
  email:
    on_success: change
    on_failure: always
